name: Clean workflow runs
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    name: Clean
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const all = await github.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              status: "completed",
              per_page:100
            });
            for (let run of all.data.workflow_runs) {
              await github.actions.deleteWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id,
              });
            }
